import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import path from "node:path";

const nodeRequire = createRequire(import.meta.url);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * `cm-bundle:` imports get their OWN bundled CodeMirror copy (used only by the
 * code-block editor). Everything reachable from such an import — including
 * @codemirror/* and @lezer/* pulled in transitively by e.g. lang-markdown — is
 * bundled into the same copy so facets/tags stay a single instance. Without
 * this, the transitive imports would fall through to the `external` list and
 * split the bundled copy across Obsidian's CM instance (broken highlighting).
 *
 * Resolution runs through a dedicated namespace because the external list is
 * matched on the raw specifier: inside the namespace we intercept every
 * @codemirror/@lezer import ourselves before externals apply.
 */
const cmBundlePlugin = {
  name: "cm-bundle",
  setup(build) {
    const CM_RE = /^cm-bundle:(.+)$/;
    const EXTERNAL_CM_RE = /^@(codemirror|lezer)\//;
    build.onResolve({ filter: /./ }, (args) => {
      const m = CM_RE.exec(args.path);
      const spec = m ? m[1] : null;
      // Transitive @codemirror/@lezer imports made from inside the bundled
      // copy stay bundled (one instance); from normal modules they fall
      // through to the global external list (Obsidian's shared CM).
      const isNested = args.namespace === "cm-bundle" && EXTERNAL_CM_RE.test(args.path);
      if (!spec && !isNested) return null;
      // Resolve bare specifiers with Node (build.resolve() applies the
      // external list, which is exactly what we must avoid here).
      return { path: nodeRequire.resolve(spec ?? args.path), namespace: "cm-bundle" };
    });
    // Modules in a custom namespace need an explicit loader.
    build.onLoad({ filter: /./, namespace: "cm-bundle" }, (args) => ({
      contents: readFileSync(args.path, "utf8"),
      loader: path.extname(args.path) === ".ts" ? "ts" : "js",
      resolveDir: path.dirname(args.path),
    }));
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // @codemirror/* and @lezer/* — EXTERNAL (official plugin convention):
  // Obsidian's loader provides the app's own CM6 instance, so our outline
  // editor shares ONE CodeMirror with the native editor and with community
  // plugins — which is what lets third-party registerEditorExtension bundles
  // (latex-suite live math preview, …) run in the outline editor.
  //
  // Exception: @codemirror/lang-markdown (and its @lezer/markdown parser) is
  // NOT among the modules Obsidian's loader provides — it is bundled here.
  // Its @codemirror/* and @lezer/common|highlight|lr imports still resolve to
  // the shared instance, so no duplicate state/view instances exist.
  external: [
    "obsidian",
    "electron",
    "@codemirror/state",
    "@codemirror/view",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/autocomplete",
    "@codemirror/search",
    "@codemirror/lint",
    "@codemirror/collab",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  plugins: [cmBundlePlugin],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
